language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq 
    - sudo apt-get install valgrind

script:
    - make

notifications:
    email:
      - hyzwowtools@gmail.com
